name: Deploy App to Server

on:
  push:
    branches:
      - feat/update-service

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/glamourreserve:latest

  deploy-prod:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Connect to server using SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo docker stop glamour
            sudo docker rm glamour
            sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/glamourreserve:latest
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/glamourreserve:latest
            sudo docker run -d -p 8080:8080 -e APPPORT=${{ secrets.APPPORT }} -e DBUSER=${{ secrets.DBUSER }} -e DBPASSWORD=${{ secrets.DBPASSWORD }} -e DBHOST=${{ secrets.DBHOST }} -e DBPORT=${{ secrets.DBPORT }} -e DBNAME=${{ secrets.DBNAME }} -e SECRETKEY=${{ secrets.SECRETKEY }} -e OPEN_AI_KEY=${{ secrets.OPEN_AI_KEY }} -e BUCKET_NAME=${{ secrets.BUCKET_NAME }} -e ACCOUNT_ID=${{ secrets.ACCOUNT_ID }} -e ACCESS_KEY_ID=${{ secrets.ACCESS_KEY_ID }} -e ACCESS_KEY_SECRET=${{ secrets.ACCESS_KEY_SECRET }} -e SMTP_SERVER=${{ secrets.SMTP_SERVER }} -e SMTP_PORT=${{ secrets.SMTP_PORT }} -e SMTP_USERNAME=${{ secrets.SMTP_USERNAME }} -e SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }} --name glamour ${{ secrets.DOCKERHUB_USERNAME }}/glamourreserve:latest
